address: ":8000"
db_path: ".\\data\\app.db"
secret: "my-secret-key"
jwt_expires: 30 #分钟
log_conf:
  log_file: "app.log"
  max_age: 7
  max_backups: 5
  max_size: 10
  compress: true
  log_level: "debug"
  log_type: "json"
