# address 服务监听端口
address: ":8000"
#db_path 数据库文件路径
db_path: ".\\data\\app.db"
#jwt签名secret
secret: "my-secret-key"
#jwt过期时间，单位分钟
jwt_expires: 30 #分钟
#日志相关配置
log_conf:
  #日志文件路径，如果有配置，则日志记录进文件，否则日志控制台输出
  log_file: "app.log"
  #日志最大保存天数，日志记录文件生效
  max_age: 7
  #日志文件保留数，仅日志文件记录生效
  max_backups: 5
  #日志文件切割大小，单位M，仅日志文件记录生效
  max_size: 10
  #是否压缩，仅日志文件记录生效
  compress: true
  #日志级别
  log_level: "debug"
  #日志格式，json text
  log_type: "json"

# 环境变量配置参考配置文件